config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index", path: "/"
    resources :users, except: [:new, :create, :show]
    resources :words, only: :index
    resources :categories do
      resources :words, except: :show
    end
    resources :block, only: [:edit, :update]
  end

  root "static_pages#home"
  get "sessions/new"
  get "sign_up" => "registers#new"
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"
  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :registers, only: [:new, :create]
  resources :categories, only: :index
  resources :words, only: :index
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :following, only: :index
  resources :followers, only: :index
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @activities = current_user.feed_activities.recent
        .paginate page: params[:page], per_page: Settings.per_page_activities
      @words = Word.includes(:answers).learned current_user.id
    end
  end
end

app/views/static_pages/home.html.erb
<div class="container">
  <%= yield %>
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-3">
        <section class="user_info">
          <%= render "shared/user_info" %>
        </section>
      </aside>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-4">
            <%= link_to words_path, class: "btn btn-info btn-large" do %>
              <i class="glyphicon glyphicon-hand-right">
              <%= t "btn_word" %></i>
            <% end %>
          </div>
          <div class="col-md-4">
            <%= link_to categories_path, class: "btn btn-info btn-large" do %>
              <i class="glyphicon glyphicon-hand-right">
              <%= t "btn_lesson" %></i>
            <% end %>
          </div>
        </div>
        <div class="col-md-12 panel panel-success">
          <div class="panel-heading">
            <h1 class="panel-title title_header"><%= t "activities" %></h1>
          </div>
          <div class="panel-body title_body">
            <%= render "shared/feed_activities" %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="center jumbotron">
      <h1><%= t "welcome" %></h1>
      <h3><%= t "warning_login" %></h3>
    </div>
  <% end %>