config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index", path: "/"
    resources :users, except: [:new, :create, :show]
    resources :words, only: :index
    resources :categories do
      resources :words, except: :show
    end
    resources :block, only: [:edit, :update]
  end

  root "static_pages#home"
  get "sessions/new"
  get "sign_up" => "registers#new"
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"
  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :registers, only: [:new, :create]
  resources :categories, only: :index
  resources :words, only: :index
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :following, only: :index
  resources :followers, only: :index
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  validates :content, presence: true,
    length: {maximum: Settings.maximum_length_content_word}
  validate :answers_quantity
  validates :content, uniqueness: true
  scope :recent, ->{order "created_at DESC"}
  scope :random, ->{order "RANDOM()"}
  scope :search_by_condition, ->condition do
    where "content LIKE ?", "%#{condition}%" if condition.present?
  end
  scope :filter_category, ->category_id do
    where category_id: category_id if category_id.present?
  end
  scope :learned, ->user_id do
    where "id IN (SELECT word_id FROM results WHERE lesson_id IN
      (SELECT id FROM lessons WHERE user_id = ?))", user_id
  end
  scope :not_learned, ->user_id do
    where "id NOT IN (SELECT word_id FROM results WHERE lesson_id IN
      (SELECT id FROM lessons WHERE user_id = ?))", user_id
  end
  scope :learned_correct, ->user_id do
    where "id IN ( SELECT r.word_id FROM results r INNER JOIN answers a
      ON r.answer_id = a.id WHERE lesson_id IN (SELECT id FROM lessons
        WHERE user_id = ?) and a.is_correct = ?)", user_id, true
  end
  scope :learned_not_correct, ->user_id do
    where "id IN ( SELECT r.word_id FROM results r INNER JOIN answers a
      ON r.answer_id = a.id WHERE lesson_id IN (SELECT id FROM lessons
        WHERE user_id = ?) and a.is_correct = ?)", user_id, false
  end

  class << self
    def to_csv
      CSV.generate do |csv|
        csv << [I18n.t("word.word"), I18n.t("word.mean")]
        all.each do |word|
          word.answers.each do |answer|
            csv << [word.content, answer.content] if answer.is_correct
          end
        end
      end
    end
  end

  private
  def answers_quantity
    errors.add :answers, I18n.t("word.answer_quanlity_error") if
      answers.size < Settings.answer_quanlity
    errors.add :answers, I18n.t("word.must_has_correct_answer_error") if
      answers.reject{|answer| !answer.is_correct?}.count == 0
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < Admin::BaseController
  before_action :load_word, except: [:index, :new, :create]
  before_action :load_category, except: [:show, :new]
  before_action :verify_category_is_block, except: :index

  def index
    @words = @category.words.includes(:answers)
      .search_by_condition(params[:search_word]).recent
      .paginate page: params[:page], per_page: Settings.per_page_words
  end

  def new
    @word = Word.new
    @word.answers.new
  end

  def create
    @word = @category.words.new word_params
    if @word.save
      flash[:success] = t "admin.word.create_success"
      redirect_to admin_category_words_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "admin.word.update_success"
      redirect_to admin_category_words_path
    else
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "word.delete_success_message"
    else
      flash[:danger] = t "word.delete_fail_message"
    end
    redirect_to admin_category_words_path
  end

  private
  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "word.not_found"
      redirect_to admin_categories_path
    end
  end

  def load_category
    @category = Category.find_by id: params[:category_id]
    unless @category
      flash[:danger] = t "admin.word.category_not_found"
      redirect_to admin_categories_path
    end
  end

  def word_params
    params.require(:word).permit :content,
      answers_attributes: [:id, :content, :is_correct]
  end

  def verify_category_is_block
    load_category
    if @category.is_block?
      flash[:danger] = t "category.message_error"
      redirect_to admin_category_words_path @category
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: :index

  def index
    @categories = Category.all
    @words_temp = if params[:condition] && params[:condition] == t("get_all")
      Word.includes(:answers).filter_category(params[:category_id])
    elsif params[:condition]
      Word.includes(:answers).filter_category(params[:category_id])
        .send(params[:condition], current_user.id)
    else
      Word.includes(:answers).search_by_condition params[:search_word]
    end.recent
    @words = @words_temp.paginate page: params[:page],
      per_page: Settings.per_page_words
    respond_to do |format|
      format.html
      format.csv{send_data @words_temp.to_csv}
      format.xls
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def index f
    @index = f.options[:child_index] + 1
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="form-group choice_question">
  <%= f.label "admin.word.answer" %>
  <div class="col-md-12">
    <div class="col-md-8 form-group">
      <%= f.text_area :content, label: false,
        placeholder: t("admin.word.answer_placeholder"),
        class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :is_correct, class: "answers_checkbox" %>
      <%= f.label :is_correct %>
    </div>
    <div class="col-md-1">
      <%= link_to_remove_fields t("admin.word.remove"), f %>
    </div>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= render "shared/error_messages", object: f.object %>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control" %>
</div>
<div id ="answers_field">
  <%= f.fields_for :answers do |answer| %>
    <%= render "answer_fields", f: answer %>
  <% end %>
  <div id ="answer_field"></div>
  <div class="add_fields" id="add_answer">
    <%= link_to_add_fields t("admin.word.add_answer"), f, :answers %>
  </div>
</div>
<%= f.submit yield(:submit_button), class: "btn btn-primary" %>

app/views/admin/words/_list_words.html.erb
<table class="table">
  <thead class="category-title">
    <tr>
      <td><%= t "word.word" %></td>
      <td><%= t "word.mean" %></td>
    </tr>
  </thead>
  <tbody>
    <%= render @words %>
  </tbody>
</table>
<%= will_paginate %>

app/views/admin/words/_search_word.html.erb
<div class="row mg-bt-12">
  <div class="col-md-6">
    <%= form_tag admin_category_words_path, method: :get, remote: true,
      id: "search-form" do %>
      <div class="input-group col-md-8">
        <%= text_field_tag :search_word, params[:search_word],
          class: "search-query form-control",
          placeholder: t("word.search_word") %>
        <span class="input-group-btn">
          <%= button_tag type: "submit",
            class: "btn btn-success margin-zero" do %>
            <i class="glyphicon glyphicon-search"></i>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.content %></td>
  <td>
    <% word.answers.each do |answer| %>
      <%= answer.content if answer.is_correct %>
    <% end %>
  </td>
  <td>
    <%= link_to edit_admin_category_word_path(@category, word),
      data: {turbolinks: false} do %>
      <span class="glyphicon glyphicon-edit"></span>
    <% end %>
  </td>
  <td>
    <%= link_to admin_category_word_path(@category, word), method: :delete,
      data: {confirm: t("admin.destroy_confirm")} do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<%= provide :title, t("admin.word.title") %>
<%= provide :submit_button, t("admin.word.update_word") %>
<div class="row" id="word">
  <div class="col-lg-12">
    <div class="col-lg-offset-2 col-md-8">
      <h2><b><%= t "admin.word.update_word" %></b></h2>
      <%= form_for [:admin, @category, @word] do |f| %>
        <%= render "form", f: f %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("word.list_words") %>
<div class="container">
  <h2 class="word-list"><%= t "word.list_words" %></h2>
  <div class="row">
    <%= render "search_word" %>
    <%= link_to t("add"), new_admin_category_word_path,
      data: {turbolinks: false}, class: "btn btn-primary" %>
  </div>
  <div id ="search_words">
    <%= render "list_words" %>
  </div>
</div>

app/views/admin/words/index.js.erb
$('#search_words').html('<%= j render "list_words" %>');

app/views/admin/words/new.html.erb
<%= provide :title, t("admin.word.title") %>
<%= provide :submit_button, t("admin.word.create_word") %>
<div class="row" id="word">
  <div class="col-lg-12">
    <div class="col-lg-offset-2 col-md-8">
      <h2><b><%= t "admin.word.create_word" %></b></h2>
      <%= form_for [:admin, :category, @word] do |f| %>
        <%= render "form", f: f %>
      <% end %>
    </div>
  </div>
</div>