config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index", path: "/"
    resources :users, except: [:new, :create, :show]
    resources :words, only: :index
    resources :categories do
      resources :words, except: :show
    end
    resources :block, only: [:edit, :update]
  end

  root "static_pages#home"
  get "sessions/new"
  get "sign_up" => "registers#new"
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"
  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :registers, only: [:new, :create]
  resources :categories, only: :index
  resources :words, only: :index
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :following, only: :index
  resources :followers, only: :index
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error_content" %> <%= pluralize object.errors.count, t("error") %>
    </div>
    <ul  class="alert alert-danger">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed_activities.html.erb
<% if @activities.any? %>
  <ul>
    <%= render @activities %>
  </ul>
  <%= will_paginate @activities %>
<% end %>

app/views/shared/_follow_user.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @user.avatar.url, class: "image" %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t("view_profile"), @user %></span>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_following_index_path @user do %>
    <strong id="following" class="stat">
      <%= @count_following %>
    </strong>
    <%= t "follow.following.title" %>
  <% end %>
  <%= link_to user_followers_path @user do %>
    <strong id="followers" class="stat">
      <%= @count_followers %>
    </strong>
    <%= t "follow.followers.title" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= image_tag current_user.avatar.url, class: "image" %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("view_profile"), current_user %></span>
<p>
  <%= t "learned" %>
  <%= @words.length %>
  <%= t "words" %>
</p>