config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index", path: "/"
    resources :users, except: [:new, :create, :show]
    resources :words, only: :index
    resources :categories do
      resources :words, except: :show
    end
    resources :block, only: [:edit, :update]
  end

  root "static_pages#home"
  get "sessions/new"
  get "sign_up" => "registers#new"
  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"
  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :registers, only: [:new, :create]
  resources :categories, only: :index
  resources :words, only: :index
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :following, only: :index
  resources :followers, only: :index
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy
  validates :title, presence: true,
    length: {maximum: Settings.maximum_length_title_category}
  validates :quantity_question, presence: true
  validates :title, uniqueness: true
  scope :recent, ->{order "created_at DESC"}
  scope :search_category, ->condition do
    where "title LIKE ?", "%#{condition}%" if condition.present?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :logged_in_user
  before_action :load_category, only: [:destroy, :edit, :update]

  def index
    @categories = Category.search_category(params[:search_category]).recent
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "category.message_success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "category.message_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "category.message_failed"
      render :edit
    end
  end

  def destroy
    if @category.words.present? && @category.lessons.present?
      flash[:danger] = t "category.destroy_failed"
    else
      if @category.destroy
        flash[:success] = t "category.destroy_message"
      else
        flash[:danger] = t "category.destroy_error"
      end
    end
      redirect_to admin_categories_path
  end

  private
  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "not_found"
      redirect_to admin_categories_path
    end
  end

  def category_params
    params.require(:category).permit :title, :quantity_question
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: :index

  def index
    @categories = Category.search_category(params[:search_category]).recent
      .paginate page: params[:page], per_page: Settings.per_page
    @lesson = Lesson.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "category.message_success"
    else
      flash[:danger] = t "category.message_failed"
    end
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit :title,
      :quantity_question
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.title %></td>
  <td><%= category.quantity_question %></td>
  <td>
    <%= link_to admin_category_words_path(category) do %>
      <span class="glyphicon glyphicon-list-alt"></span>
    <% end %>
  </td>
  <td>
    <%= link_to edit_admin_category_path(category) do %>
      <span class="glyphicon glyphicon-edit"></span>
    <% end %>
  </td>
  <td>
    <%= link_to [:admin, category], method: :delete,
      data: {confirm: t("admin.destroy_confirm")} do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
  <td>
    <%= form_tag admin_block_path(category.id), method: :patch do %>
      <%= check_box_tag :is_block, {}, category.is_block,
        onclick: "changeStatus(this)" %>
      <%= t "category.is_block" %>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_list_categories.html.erb
<table class="table">
  <thead>
    <tr>
      <td><%= t "category.categories" %></td>
      <td><%= t "category.quanlity_word" %></td>
    </tr>
  </thead>
  <tbody>
    <%= render @categories %>
  </tbody>
</table>
<%= will_paginate %>

app/views/admin/categories/_search_index_categories.html.erb
<div class="container">
  <div class="row center">
    <div class="col-sm-6 col-sm-offset-3 margin-top">
      <%= form_tag categories_path, method: :get, remote: true,
        class: "form-inline" do %>
        <%= search_field_tag :search_category, params[:search_category],
          placeholder: t("category.search_categories"),
          class: "form-control search-field" %>
        <%= button_tag(type: "submit", class: "btn-primary") do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t("category.update_title") %>
<h2><%= t "category.update_title" %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :quantity_question %>
        <%= f.text_field :quantity_question, class: "form-control" %>
      </div>

      <%= f.submit t("update.button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("category.categories") %>
<div class="container">
  <h2 class="word-list"><%= t "list_categories" %></h2>
  <%= render "search_index_categories" %>
  <h2><%= link_to t("category.btn_create"), new_admin_category_path,
    class: "btn-create" %></h2>
  <div id ="categories_filter">
    <%= render "list_categories" %>
  </div>
</div>

app/views/admin/categories/index.js.erb
$('#categories_filter').html('<%= j render 'list_categories' %>');

app/views/admin/categories/new.html.erb
<% provide :title, t("categories") %>
<h2><%= t "categories" %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :quantity_question %>
      <%= f.text_field :quantity_question, class: "form-control" %>

      <%= f.submit t("category.btn_create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>